In [1]:
import numpy as np 
import pandas as pd

In [2]:
df = pd.read_csv("tips.csv")

In [4]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [5]:
df["total_bill"] > 25

0      False
1      False
2      False
3      False
4      False
       ...
239     True
240     True
241    False
242    False
243    False
Name: total_bill, Length: 244, dtype: bool

In [7]:
df[df["total_bill"] > 25] # it gives all the instances where the total bill is atleast 25

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
5,25.29,4.71,Male,No,Sun,Dinner,4,6.32,Erik Smith,213140353657882,Sun9679
7,26.88,3.12,Male,No,Sun,Dinner,4,6.72,Robert Buck,3514785077705092,Sun8157
11,35.26,5.00,Female,No,Sun,Dinner,4,8.82,Diane Macias,4577817359320969,Sun6686
23,39.42,7.58,Male,No,Sat,Dinner,4,9.86,Lance Peterson,3542584061609808,Sat239
39,31.27,5.00,Male,No,Sat,Dinner,3,10.42,Mr. Brandon Berry,6011525851069856,Sat6373
44,30.40,5.60,Male,No,Sun,Dinner,4,7.60,Todd Cooper,503846761263,Sun2274
47,32.40,6.00,Male,No,Sun,Dinner,4,8.10,James Barnes,3552002592874186,Sun9677
48,28.55,2.05,Male,No,Sun,Dinner,3,9.52,Austin Fisher,6011481668986587,Sun4142
52,34.81,5.20,Female,No,Sun,Dinner,4,8.70,Emily Daniel,4291280793094374,Sun6165
54,25.56,4.34,Male,No,Sun,Dinner,4,6.39,Ronald Owens,6569607991983380,Sun9470
56,38.01,3.00,Male,Yes,Sat,Dinner,4,9.50,James Christensen DDS,349793629453226,Sat8903
57,26.41,1.50,Female,No,Sat,Dinner,2,13.20,Melody Simon,4745394421258160,Sat8980
59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,6596453823950595,Sat8139
72,26.86,3.14,Female,Yes,Sat,Dinner,2,13.43,Victoria Obrien MD,4216245673726,Sat1967
73,25.28,5.00,Female,Yes,Sat,Dinner,2,12.64,Julie Holmes,5418689346409571,Sat6065
77,27.20,4.00,Male,No,Thur,Lunch,4,6.80,John Davis,30344778738589,Thur4924
83,32.68,5.00,Male,Yes,Thur,Lunch,2,16.34,Daniel Murphy,5356177501009133,Thur8801
85,34.83,5.17,Female,No,Thur,Lunch,4,8.71,Shawna Cook,6011787464177340,Thur7972
90,28.97,3.00,Male,Yes,Fri,Dinner,2,14.48,Daniel Mason,3597456900644078,Fri4175
95,40.17,4.73,Male,Yes,Fri,Dinner,4,10.04,Aaron Bentley,180026611638690,Fri9628
96,27.28,4.00,Male,Yes,Fri,Dinner,2,13.64,Eric Carter,4563054452787961,Fri3159
102,44.30,2.50,Female,Yes,Sat,Dinner,3,14.77,Heather Cohen,379771118886604,Sat6240
107,25.21,4.29,Male,Yes,Sat,Dinner,2,12.60,Jason Mullen,4738781782868,Sat5196
112,38.07,4.00,Male,No,Sun,Dinner,3,12.69,Jeff Lopez,3572865915176463,Sun591
114,25.71,4.00,Female,No,Sun,Dinner,3,8.57,Katie Smith,5400160161311292,Sun6492
116,29.93,5.07,Male,No,Sun,Dinner,4,7.48,Shawn Blake,4689079711213722,Sun22
125,29.80,4.20,Female,No,Thur,Lunch,6,4.97,Angela Sanchez,503857080488,Thur3948
141,34.30,6.70,Male,No,Thur,Lunch,6,5.72,Steven Carlson,3526515703718508,Thur1025
142,41.19,5.00,Male,No,Thur,Lunch,5,8.24,Eric Andrews,4356531761046453,Thur3621
143,27.05,5.00,Female,No,Thur,Lunch,6,4.51,Regina Jones,4311048695487,Thur6179
155,29.85,5.14,Female,No,Sun,Dinner,5,5.97,Madison Wilson,4210875236164664,Sun9176
156,48.17,5.00,Male,No,Sun,Dinner,6,8.03,Ryan Gonzales,3523151482063321,Sun7518
167,31.71,4.50,Male,No,Sun,Dinner,4,7.93,Michael Lawson,3566285921227119,Sun3719
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5473850968388236,Sat1954
173,31.85,3.18,Male,Yes,Sun,Dinner,2,15.92,Scott Perez,3577115550328507,Sun9335
175,32.90,3.11,Male,Yes,Sun,Dinner,2,16.45,Nathan Reynolds,370307040837149,Sun5109
179,34.63,3.55,Male,Yes,Sun,Dinner,2,17.32,Brian Bailey,346656312114848,Sun9851
180,34.65,3.68,Male,Yes,Sun,Dinner,4,8.66,James Hebert DDS,676168737648,Sun7544
182,45.35,3.50,Male,Yes,Sun,Dinner,3,15.12,Jose Parsons,4112207559459910,Sun2337
184,40.55,3.00,Male,Yes,Sun,Dinner,2,20.27,Stephen Cox,3547798222044029,Sun5140
187,30.46,2.00,Male,Yes,Sun,Dinner,5,6.09,David Barrett,4792882899700988,Sun9987
192,28.44,2.56,Male,Yes,Thur,Lunch,2,14.22,Dr. Jeffrey Rich,4737538358295,Thur4334
197,43.11,5.00,Female,Yes,Thur,Lunch,4,10.78,Brooke Soto,5544902205760175,Thur9313
206,26.59,3.41,Male,Yes,Sat,Dinner,3,8.86,Daniel Owens,38971087967574,Sat1
207,38.73,3.00,Male,Yes,Sat,Dinner,4,9.68,Ricky Ramirez,347817964484033,Sat4505
210,30.06,2.00,Male,Yes,Sat,Dinner,3,10.02,Shawn Mendoza,30184049218122,Sat8361
211,25.89,5.16,Male,Yes,Sat,Dinner,4,6.47,Christopher Li,6011962464150569,Sat6735
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,676218815212,Sat4590
214,28.17,6.50,Female,Yes,Sat,Dinner,3,9.39,Marissa Jackson,4922302538691962,Sat3374
216,28.15,3.00,Male,Yes,Sat,Dinner,5,5.63,Shawn Barnett PhD,4590982568244,Sat7320
219,30.14,3.09,Female,Yes,Sat,Dinner,4,7.54,Shelby House,502097403252,Sat8863
237,32.83,1.17,Male,Yes,Sat,Dinner,2,16.42,Thomas Brown,4284722681265508,Sat2929
238,35.83,4.67,Female,No,Sat,Dinner,3,11.94,Kimberly Crane,676184013727,Sat9777
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766

In [8]:
df[df["sex"] == "Male"] # To filter all male customer in our data frame

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
5,25.29,4.71,Male,No,Sun,Dinner,4,6.32,Erik Smith,213140353657882,Sun9679
6,8.77,2.00,Male,No,Sun,Dinner,2,4.38,Kristopher Johnson,2223727524230344,Sun5985
...,...,...,...,...,...,...,...,...,...,...,...
236,12.60,1.00,Male,Yes,Sat,Dinner,2,6.30,Matthew Myers,3543676378973965,Sat5032
237,32.83,1.17,Male,Yes,Sat,Dinner,2,16.42,Thomas Brown,4284722681265508,Sat2929
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17

### Multiple conditions

* AND ----> &
* OR ---> | # pipe operator
* NOT ----> ~

In [10]:
df[(df["tip"]>5) & (df["sex"] == "Female")]  # that is female customer who paid the tip > 7

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
52,34.81,5.20,Female,No,Sun,Dinner,4,8.70,Emily Daniel,4291280793094374,Sun6165
85,34.83,5.17,Female,No,Thur,Lunch,4,8.71,Shawna Cook,6011787464177340,Thur7972
155,29.85,5.14,Female,No,Sun,Dinner,5,5.97,Madison Wilson,4210875236164664,Sun9176
214,28.17,6.50,Female,Yes,Sat,Dinner,3,9.39,Marissa Jackson,4922302538691962,Sat3374

In [18]:
# Q1 I want to get all the records where tip is < 2 and total bill is above 10

df[(df["tip"] < 2) & (df["total_bill"] > 10)]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
8,15.04,1.96,Male,No,Sun,Dinner,2,7.52,Joseph Mcdonald,3522866365840377,Sun6820
10,10.27,1.71,Male,No,Sun,Dinner,2,5.14,William Riley,566287581219,Sun2546
12,15.42,1.57,Male,No,Sun,Dinner,2,7.71,Chad Harrington,577040572932,Sun1300
16,10.33,1.67,Female,No,Sun,Dinner,3,3.44,Elizabeth Foster,4240025044626033,Sun9715
57,26.41,1.50,Female,No,Sat,Dinner,2,13.20,Melody Simon,4745394421258160,Sat8980
58,11.24,1.76,Male,Yes,Sat,Dinner,2,5.62,Troy Guerrero,3560782621035582,Sat6683
62,11.02,1.98,Male,Yes,Sat,Dinner,2,5.51,Joseph Hart,180046232326178,Sat2265
70,12.02,1.97,Male,No,Sat,Dinner,2,6.01,Max Brown,213139760497718,Sat2100
75,10.51,1.25,Male,No,Sat,Dinner,2,5.26,Kenneth Hayes,213142079731108,Sat5056
82,10.07,1.83,Female,No,Thur,Lunch,1,10.07,Julie Moody,630413282843,Thur4909
97,12.03,1.50,Male,Yes,Fri,Dinner,2,6.02,Eric Herrera,580116092652,Fri9268
99,12.46,1.50,Male,No,Fri,Dinner,2,6.23,Edward Carter,347435564751626,Fri5575
105,15.36,1.64,Male,Yes,Sat,Dinner,2,7.68,David Price,4029957452720,Sat5106
117,10.65,1.50,Female,No,Thur,Lunch,2,5.32,Linda Zhang,3560509622598239,Thur9593
118,12.43,1.80,Female,No,Thur,Lunch,2,6.22,Dr. Caroline Tucker,502047186908,Thur8084
121,13.42,1.68,Female,No,Thur,Lunch,2,6.71,Laura Garcia,5181484390945653,Thur2158
130,19.08,1.50,Male,No,Thur,Lunch,2,9.54,Seth Sexton,213113680829581,Thur1446
132,11.17,1.50,Female,No,Thur,Lunch,2,5.58,Taylor Gonzalez,6011990685390011,Thur7783
146,18.64,1.36,Female,No,Thur,Lunch,3,6.21,Kelly Estrada,60463302327,Thur3941
147,11.87,1.63,Female,No,Thur,Lunch,2,5.94,Annette Cunningham,675937746864,Thur4780
168,10.59,1.61,Female,Yes,Sat,Dinner,2,5.30,Sara Jimenez,502053147208,Sat9795
190,15.69,1.50,Male,Yes,Sun,Dinner,2,7.84,Riley Barnes,180053549128800,Sun5104
215,12.90,1.10,Female,Yes,Sat,Dinner,2,6.45,Jessica Owen,4726904879471,Sat6983
217,11.59,1.50,Male,Yes,Sat,Dinner,2,5.80,Gary Orr,30324521283406,Sat8489
224,13.42,1.58,Male,Yes,Fri,Lunch,2,6.71,Ronald Vaughn DVM,341503466406403,Fri5959
233,10.77,1.47,Male,No,Sat,Dinner,2,5.38,Paul Novak,6011698897610858,Sat1467
235,10.07,1.25,Male,No,Sat,Dinner,2,5.04,Sean Gonzalez,3534021246117605,Sat4615
236,12.60,1.00,Male,Yes,Sat,Dinner,2,6.30,Matthew Myers,3543676378973965,Sat5032
237,32.83,1.17,Male,Yes,Sat,Dinner,2,16.42,Thomas Brown,4284722681265508,Sat2929
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17

In [32]:
# I want all customers list who visited resturant on weekend 
# Filter for weekend days
#weekend_df = df[df['day'].isin(['Sat', 'Sun'])]

# Optionally, show just the customer names
#customers = weekend_df['Payer Name'].tolist()

#print(customers)
df[df['day'].isin(['Sat', 'Sun'])]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
238,35.83,4.67,Female,No,Sat,Dinner,3,11.94,Kimberly Crane,676184013727,Sat9777
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17

In [34]:
df[(df["day"] == "Sat" ) | (df["day"] == "Sun")]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
238,35.83,4.67,Female,No,Sat,Dinner,3,11.94,Kimberly Crane,676184013727,Sat9777
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17

In [35]:
# to verify 
df1 = df[(df["day"] == "Sat" ) | (df["day"] == "Sun")] 
df1["day"].value_counts()

Sat    87
Sun    76
Name: day, dtype: int64

In [39]:
# or the above can be done by 
# Filter for weekend days
weekend_df = df[df['day'].isin(['Sat', 'Sun'])]

# Optionally, show just the customer names
customers = weekend_df['Payer Name'].tolist()

print(customers)

['Christy Cunningham', 'Douglas Tucker', 'Travis Walters', 'Nathaniel Harris', 'Tonya Carter', 'Erik Smith', 'Kristopher Johnson', 'Robert Buck', 'Joseph Mcdonald', 'Jerome Abbott', 'William Riley', 'Diane Macias', 'Chad Harrington', 'Joshua Jones', 'Vanessa Jones', 'Matthew Reilly', 'Elizabeth Foster', 'John Pittman', 'Laura Martinez', 'Timothy Oneal', 'Thomas Rice', 'Natalie Gardner', 'Ashley Shelton', 'Lance Peterson', 'Christopher Ross', 'Robert Perkins', 'Kyle Avery', 'Patrick Barber', 'David Collier', 'Melinda Murphy', 'Grant Hall', 'Danny Santiago', 'Amanda Wilson', 'Amber Francis', 'Jacob Castillo', 'Joseph Mullins', 'William Ford', 'Erin Lewis', 'Brandon Bradley', 'Mr. Brandon Berry', 'Adam Edwards', 'David Boyer', 'Bryan Brown', 'Christopher Spears', 'Todd Cooper', 'Richard Fitzgerald', 'Joshua Gilmore', 'James Barnes', 'Austin Fisher', 'William Roth', 'Jeremiah Neal', 'Jessica Ibarra', 'Emily Daniel', 'Curtis Morgan', 'Ronald Owens', 'Michael Hamilton', 'James Christensen DDS', 'Melody Simon', 'Troy Guerrero', 'Brian Ortiz', 'Anthony Mclean', 'Ryan Hernandez', 'Joseph Hart', 'Chad Hart', 'Michael Johnson', 'Justin Dixon', 'Rachel Vaughn', 'Tiffany Brock', 'Mr. Travis Bailey Jr.', 'Adam Hall', 'Max Brown', 'Teresa Fisher', 'Victoria Obrien MD', 'Julie Holmes', 'Ashley Harris', 'Kenneth Hayes', 'Mark Smith', 'Heather Cohen', 'Kathleen Hawkins', 'Gabrielle Frederick', 'David Price', 'Karl Mcdaniel', 'Jason Mullen', 'Steven Grant', 'Amanda Anderson', 'James Sanchez', 'Terri Jones', 'Jeff Lopez', 'John Joyce', 'Katie Smith', 'Kayla Stone', 'Shawn Blake', 'Luke Rice', 'Jason Arnold', 'Gregory Smith', 'Todd Patterson', 'James Smith', 'Madison Wilson', 'Ryan Gonzales', 'Laura Robles', 'Ashley Boyd', 'Christopher Soto', 'Travis Gonzalez', 'Brandon Oconnor', 'Jennifer Baird', 'Charles Newton', 'Audrey Griffin', 'Jacob Hansen', 'Gordon Lane', 'Michael Lawson', 'Sara Jimenez', 'Amy Hill', 'Gregory Clark', 'David Hall', 'Larry White', 'Scott Perez', 'Brian Miles', 'Nathan Reynolds', 'Walter Simmons', 'John Dudley', 'Melanie Gray', 'Brian Bailey', 'James Hebert DDS', 'Jason Cox', 'Jose Parsons', 'Dr. Michael James', 'Stephen Cox', 'Joseph Howell', 'Heidi Atkinson', 'David Barrett', 'Glenda Wiggins', 'Richard Stevens', 'Riley Barnes', 'Daniel Owens', 'Ricky Ramirez', 'Jason Carter', 'Sarah Cunningham', 'Shawn Mendoza', 'Christopher Li', 'Alex Williamson', 'Robin Andersen', 'Marissa Jackson', 'Jessica Owen', 'Shawn Barnett PhD', 'Gary Orr', 'Nicholas Archer', 'Shelby House', 'Robert Bradley', 'Glenn Jones', 'Jennifer Russell', 'Michael Osborne', 'Jason Parks', 'James Taylor', 'Paul Novak', 'Tracy Douglas', 'Sean Gonzalez', 'Matthew Myers', 'Thomas Brown', 'Kimberly Crane', 'Michael Avila', 'Monica Sanders', 'Keith Wong', 'Dennis Dixon']

In [37]:
#I want all the smokers  who visted on thursday and bill is is less than 15 
df[(df["smoker"] == "Yes") & (df["total_bill"] < 15) & (df["day"].isin(["Thur"]))]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
196,10.34,2.00,Male,Yes,Thur,Lunch,2,5.17,Eric Martin,30442491190342,Thur9862
198,13.00,2.00,Female,Yes,Thur,Lunch,2,6.50,Katherine Bond,4926725945192,Thur437
199,13.51,2.00,Male,Yes,Thur,Lunch,2,6.76,Joseph Murphy MD,6547218923471275,Thur2428
201,12.74,2.01,Female,Yes,Thur,Lunch,2,6.37,Abigail Parks,3586645396220590,Thur2544
202,13.00,2.00,Female,Yes,Thur,Lunch,2,6.50,Ashley Shaw,180088043008041,Thur1301

In [38]:
#I want all the entries where customers are either not female or give a tip higher that 6. 
#All rows where:

   # the customer is male, or

   # the tip they gave is more than 6, even if they are female.

df[(df["sex"] != "Female") | (df["tip"] > 6)]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
5,25.29,4.71,Male,No,Sun,Dinner,4,6.32,Erik Smith,213140353657882,Sun9679
6,8.77,2.00,Male,No,Sun,Dinner,2,4.38,Kristopher Johnson,2223727524230344,Sun5985
...,...,...,...,...,...,...,...,...,...,...,...
236,12.60,1.00,Male,Yes,Sat,Dinner,2,6.30,Matthew Myers,3543676378973965,Sat5032
237,32.83,1.17,Male,Yes,Sat,Dinner,2,16.42,Thomas Brown,4284722681265508,Sat2929
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17

In [40]:
# to verify 
df2 = df[(df["sex"] != "Female") | (df["tip"] > 6)]

df2["sex"].value_counts()

Male      157
Female      1
Name: sex, dtype: int64

In [44]:
 df[~(df["sex"] == "Female") | (df["tip"] > 6)]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
5,25.29,4.71,Male,No,Sun,Dinner,4,6.32,Erik Smith,213140353657882,Sun9679
6,8.77,2.00,Male,No,Sun,Dinner,2,4.38,Kristopher Johnson,2223727524230344,Sun5985
...,...,...,...,...,...,...,...,...,...,...,...
236,12.60,1.00,Male,Yes,Sat,Dinner,2,6.30,Matthew Myers,3543676378973965,Sat5032
237,32.83,1.17,Male,Yes,Sat,Dinner,2,16.42,Thomas Brown,4284722681265508,Sat2929
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17

###  .isin()

In [42]:
condition = ['Sat', 'Sun']
df[df["day"].isin(condition)]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
238,35.83,4.67,Female,No,Sat,Dinner,3,11.94,Kimberly Crane,676184013727,Sat9777
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17