In [1]:
import numpy as np 
import pandas as pd

In [2]:
# look into pandas reference.

In [3]:
df = pd.read_csv('tips.csv')

In [4]:
df.head(3)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458

###  Apply method

In [8]:
def sq(num):
    return np.round(num**2,2)

In [9]:
sq(3.4)

11.56

In [11]:
df['tip'].apply(sq)  # we squared all the numbers in the tip

0       1.02
1       2.76
2      12.25
3      10.96
4      13.03
       ...
239    35.05
240     4.00
241     4.00
242     3.06
243     9.00
Name: tip, Length: 244, dtype: float64

In [12]:
# To find len of string 
def length(s):
    return len(s)

In [13]:
df["Payer Name"].apply(length)

0      18
1      14
2      14
3      16
4      12
       ..
239    13
240    14
241    10
242    12
243    15
Name: Payer Name, Length: 244, dtype: int64

In [14]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [19]:
 #  i want to mask some portion of ctredit card number 
def last_four(num):
    return "*"*12 + str(num)[-4:] # 12 astrists +(concatanate)  last four digit

In [18]:
last_four(45678909764345)

'************4345'

In [20]:
df["CC Number"].apply(last_four)

0      ************3410
1      ************9230
2      ************1322
3      ************5994
4      ************7221
             ...
239    ************2842
240    ************5404
241    ************7196
242    ************0950
243    ************8139
Name: CC Number, Length: 244, dtype: object

In [21]:
df["masked_CC"] = df["CC Number"].apply(last_four)

In [22]:
df

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,masked_CC
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,************3410
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,************9230
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,************1322
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,************5994
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,************7221
...,...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657,************2842
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766,************5404
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880,************7196
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17,************0950
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672,************8139

### Using lambda

In [25]:
 df["CC Number"].apply( lambda num: "*"*12 + str(num)[-4:])

0      ************3410
1      ************9230
2      ************1322
3      ************5994
4      ************7221
             ...
239    ************2842
240    ************5404
241    ************7196
242    ************0950
243    ************8139
Name: CC Number, Length: 244, dtype: object

In [26]:
# Rate the customer based on bill > 30 : rate them base on some star 

def ratings(price):
    if price < 10:
        return "*"
    elif price >= 10 and price < 30:
        return "**" 
    else:
        return "***"

In [27]:
ratings(34)

'***'

In [28]:
df["total_bill"].apply(ratings)

0      **
1      **
2      **
3      **
4      **
       ..
239    **
240    **
241    **
242    **
243    **
Name: total_bill, Length: 244, dtype: object

In [29]:
df["customer_kind"] = df["total_bill"].apply(ratings)

In [30]:
df

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,masked_CC,customer_kind
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,************3410,**
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,************9230,**
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,************1322,**
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,************5994,**
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,************7221,**
...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657,************2842,**
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766,************5404,**
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880,************7196,**
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17,************0950,**
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672,************8139,**

In [31]:
df[df["customer_kind"] == "***"]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,masked_CC,customer_kind
11,35.26,5.00,Female,No,Sun,Dinner,4,8.82,Diane Macias,4577817359320969,Sun6686,************0969,***
23,39.42,7.58,Male,No,Sat,Dinner,4,9.86,Lance Peterson,3542584061609808,Sat239,************9808,***
39,31.27,5.00,Male,No,Sat,Dinner,3,10.42,Mr. Brandon Berry,6011525851069856,Sat6373,************9856,***
44,30.40,5.60,Male,No,Sun,Dinner,4,7.60,Todd Cooper,503846761263,Sun2274,************1263,***
47,32.40,6.00,Male,No,Sun,Dinner,4,8.10,James Barnes,3552002592874186,Sun9677,************4186,***
52,34.81,5.20,Female,No,Sun,Dinner,4,8.70,Emily Daniel,4291280793094374,Sun6165,************4374,***
56,38.01,3.00,Male,Yes,Sat,Dinner,4,9.50,James Christensen DDS,349793629453226,Sat8903,************3226,***
59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,6596453823950595,Sat8139,************0595,***
83,32.68,5.00,Male,Yes,Thur,Lunch,2,16.34,Daniel Murphy,5356177501009133,Thur8801,************9133,***
85,34.83,5.17,Female,No,Thur,Lunch,4,8.71,Shawna Cook,6011787464177340,Thur7972,************7340,***
95,40.17,4.73,Male,Yes,Fri,Dinner,4,10.04,Aaron Bentley,180026611638690,Fri9628,************8690,***
102,44.30,2.50,Female,Yes,Sat,Dinner,3,14.77,Heather Cohen,379771118886604,Sat6240,************6604,***
112,38.07,4.00,Male,No,Sun,Dinner,3,12.69,Jeff Lopez,3572865915176463,Sun591,************6463,***
141,34.30,6.70,Male,No,Thur,Lunch,6,5.72,Steven Carlson,3526515703718508,Thur1025,************8508,***
142,41.19,5.00,Male,No,Thur,Lunch,5,8.24,Eric Andrews,4356531761046453,Thur3621,************6453,***
156,48.17,5.00,Male,No,Sun,Dinner,6,8.03,Ryan Gonzales,3523151482063321,Sun7518,************3321,***
167,31.71,4.50,Male,No,Sun,Dinner,4,7.93,Michael Lawson,3566285921227119,Sun3719,************7119,***
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5473850968388236,Sat1954,************8236,***
173,31.85,3.18,Male,Yes,Sun,Dinner,2,15.92,Scott Perez,3577115550328507,Sun9335,************8507,***
175,32.90,3.11,Male,Yes,Sun,Dinner,2,16.45,Nathan Reynolds,370307040837149,Sun5109,************7149,***
179,34.63,3.55,Male,Yes,Sun,Dinner,2,17.32,Brian Bailey,346656312114848,Sun9851,************4848,***
180,34.65,3.68,Male,Yes,Sun,Dinner,4,8.66,James Hebert DDS,676168737648,Sun7544,************7648,***
182,45.35,3.50,Male,Yes,Sun,Dinner,3,15.12,Jose Parsons,4112207559459910,Sun2337,************9910,***
184,40.55,3.00,Male,Yes,Sun,Dinner,2,20.27,Stephen Cox,3547798222044029,Sun5140,************4029,***
187,30.46,2.00,Male,Yes,Sun,Dinner,5,6.09,David Barrett,4792882899700988,Sun9987,************0988,***
197,43.11,5.00,Female,Yes,Thur,Lunch,4,10.78,Brooke Soto,5544902205760175,Thur9313,************0175,***
207,38.73,3.00,Male,Yes,Sat,Dinner,4,9.68,Ricky Ramirez,347817964484033,Sat4505,************4033,***
210,30.06,2.00,Male,Yes,Sat,Dinner,3,10.02,Shawn Mendoza,30184049218122,Sat8361,************8122,***
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,676218815212,Sat4590,************5212,***
219,30.14,3.09,Female,Yes,Sat,Dinner,4,7.54,Shelby House,502097403252,Sat8863,************3252,***
237,32.83,1.17,Male,Yes,Sat,Dinner,2,16.42,Thomas Brown,4284722681265508,Sat2929,************5508,***
238,35.83,4.67,Female,No,Sat,Dinner,3,11.94,Kimberly Crane,676184013727,Sat9777,************3727,***

In [37]:
# create a new column gives final bill 
# Total bill + 5% GST 
def final_bill(num):
    return num + 0.05*num

In [44]:
final_bill(10)

10.5

In [35]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,masked_CC,customer_kind
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,************3410,**
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,************9230,**
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,************1322,**
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,************5994,**
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,************7221,**

In [45]:
df["total_bill"].apply(final_bill)

#df["final_bill"] = df["total_bill"].apply(lambda x: np.round(1.05*x, 2))

0      17.8395
1      10.8570
2      22.0605
3      24.8640
4      25.8195
        ...
239    30.4815
240    28.5390
241    23.8035
242    18.7110
243    19.7190
Name: total_bill, Length: 244, dtype: float64

In [46]:
df["final_bill"] = df["total_bill"].apply(final_bill)

In [47]:
df

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,masked_CC,customer_kind,final_bill,is_generous
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,************3410,**,17.8395,False
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,************9230,**,10.8570,False
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,************1322,**,22.0605,False
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,************5994,**,24.8640,False
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,************7221,**,25.8195,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657,************2842,**,30.4815,True
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766,************5404,**,28.5390,False
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880,************7196,**,23.8035,False
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17,************0950,**,18.7110,False
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672,************8139,**,19.7190,False

In [48]:
# df["is_generous" ] being true if tip is > 20 % of total bill else false 
df["is_generous"] = df["tip"] > 0.2 * df["total_bill"]

In [49]:
df

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,masked_CC,customer_kind,final_bill,is_generous
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,************3410,**,17.8395,False
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,************9230,**,10.8570,False
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,************1322,**,22.0605,False
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,************5994,**,24.8640,False
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,************7221,**,25.8195,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657,************2842,**,30.4815,True
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766,************5404,**,28.5390,False
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880,************7196,**,23.8035,False
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17,************0950,**,18.7110,False
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672,************8139,**,19.7190,False

In [51]:
df.apply(lambda sample: sample["tip"]>0.2 * sample["total_bill"], axis = 1) # sample is like a place holder for  any  sample

0      False
1      False
2      False
3      False
4      False
       ...
239     True
240    False
241    False
242    False
243    False
Length: 244, dtype: bool