In [2]:
# Missing Data 
# Many ml model or Statistical mode cant work with missing data. 
# In old pandas it will display NAN for missing data 
# Newer pandas is have specialized null pandas values pd.NaT to imply missing values. 

# option for dealing with missing data
#1.Keep it 
#2.Remove it
#3.Replace it. 

import numpy as np
import pandas as pd

In [3]:
np.nan

nan

In [4]:
type(np.nan)

float

In [5]:
pd.NA # it is introduce to show/ represent the missing value

In [6]:
type(pd.NA)

pandas._libs.missing.NAType

In [7]:
pd.NaT

NaT

In [8]:
type(pd.NaT)

pandas._libs.tslibs.nattype.NaTType

#### Checking and Selecting Null Values

In [9]:
df = pd.read_csv('movie_scores.csv')

In [10]:
df

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [11]:
df.isnull() # Work in the context of data frame.

   first_name  last_name    age    sex  pre_movie_score  post_movie_score
0       False      False  False  False            False             False
1        True       True   True   True             True              True
2       False      False  False  False             True              True
3       False      False  False  False            False             False
4       False      False  False  False            False             False

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   first_name        4 non-null      object
 1   last_name         4 non-null      object
 2   age               4 non-null      float64
 3   sex               4 non-null      object
 4   pre_movie_score   3 non-null      float64
 5   post_movie_score  3 non-null      float64
dtypes: float64(3), object(3)
memory usage: 368.0+ bytes

In [13]:
df.isna()

   first_name  last_name    age    sex  pre_movie_score  post_movie_score
0       False      False  False  False            False             False
1        True       True   True   True             True              True
2       False      False  False  False             True              True
3       False      False  False  False            False             False
4       False      False  False  False            False             False

In [14]:
df.isna().sum() # To see how many missing values are there. in each column. U can use df.info() also

first_name          1
last_name           1
age                 1
sex                 1
pre_movie_score     2
post_movie_score    2
dtype: int64

In [15]:
df.notnull()

   first_name  last_name    age    sex  pre_movie_score  post_movie_score
0        True       True   True   True             True              True
1       False      False  False  False            False             False
2        True       True   True   True            False             False
3        True       True   True   True             True              True
4        True       True   True   True             True              True

In [16]:
df.notnull().sum()

first_name          4
last_name           4
age                 4
sex                 4
pre_movie_score     3
post_movie_score    3
dtype: int64

In [17]:
df['first_name']

0      Tom
1      NaN
2     Hugh
3    Oprah
4     Emma
Name: first_name, dtype: object

In [18]:
type(df['first_name'])

pandas.core.series.Series

In [19]:
df['first_name'].notnull()

0     True
1    False
2     True
3     True
4     True
Name: first_name, dtype: bool

In [20]:
df['first_name'].notnull().sum()

4

In [21]:
# Now u can use above as a conditional filtering for entitre data frame 
df[df['first_name'].notnull()] # get all the values for which this first name can be null.

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
2       Hugh   Jackman  51.0   m              NaN               NaN
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [22]:
# Conditional filtering based on two columns 
df['pre_movie_score'].isnull()

0    False
1     True
2     True
3    False
4    False
Name: pre_movie_score, dtype: bool

In [23]:
df['sex'].notnull()

0     True
1    False
2     True
3     True
4     True
Name: sex, dtype: bool

In [24]:
# I want all thevalues in which the pre movie score is null andsex is not null 
df[df['pre_movie_score'].isnull() & df['sex'].notnull()]

  first_name last_name   age sex  pre_movie_score  post_movie_score
2       Hugh   Jackman  51.0   m              NaN               NaN

In [25]:
df

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

#### Drop Data

In [26]:
df.dropna() # it drops all the row wihich have NAN value

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [27]:
df.dropna(thresh = 1 ) # that is there should be atleast one non null value in that row

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
2       Hugh   Jackman  51.0   m              NaN               NaN
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [28]:
df.dropna(thresh = 4 )

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
2       Hugh   Jackman  51.0   m              NaN               NaN
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [29]:
df.dropna(thresh = 5 ) # I need 5 non null values

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [30]:

 #I want drom column with missing values (default axis = 0 ie: row wise)  
df.dropna(axis = 1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [31]:
df.dropna(axis = 1,thresh = 1)

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [32]:
df.dropna(axis = 1,thresh = 4) # i want atleast 4 non-null values in the column.

  first_name last_name   age  sex
0        Tom     Hanks  63.0    m
1        NaN       NaN   NaN  NaN
2       Hugh   Jackman  51.0    m
3      Oprah   Winfrey  66.0    f
4       Emma     Stone  31.0    f

### Fill data

In [33]:
df

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [34]:
df.fillna('EMPTY')

  first_name last_name    age    sex pre_movie_score post_movie_score
0        Tom     Hanks   63.0      m             8.0             10.0
1      EMPTY     EMPTY  EMPTY  EMPTY           EMPTY            EMPTY
2       Hugh   Jackman   51.0      m           EMPTY            EMPTY
3      Oprah   Winfrey   66.0      f             6.0              8.0
4       Emma     Stone   31.0      f             7.0              9.0

In [35]:
df['first_name']

0      Tom
1      NaN
2     Hugh
3    Oprah
4     Emma
Name: first_name, dtype: object

In [36]:
df['first_name'].fillna('DEMO NAME')

0          Tom
1    DEMO NAME
2         Hugh
3        Oprah
4         Emma
Name: first_name, dtype: object

In [37]:
df

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [38]:
df['pre_movie_score'].mean()

7.0

In [39]:
df['pre_movie_score'].fillna(df['pre_movie_score'].mean())

0    8.0
1    7.0
2    7.0
3    6.0
4    7.0
Name: pre_movie_score, dtype: float64

In [40]:
df.mean(numeric_only =  True)

age                 52.75
pre_movie_score      7.00
post_movie_score     9.00
dtype: float64

In [41]:
df.fillna(df.mean(numeric_only =  True))

  first_name last_name    age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.00    m              8.0              10.0
1        NaN       NaN  52.75  NaN              7.0               9.0
2       Hugh   Jackman  51.00    m              7.0               9.0
3      Oprah   Winfrey  66.00    f              6.0               8.0
4       Emma     Stone  31.00    f              7.0               9.0

#### Filling with Interpolation

In [42]:
# Dictionary 
rail_tickt = {'first':100,
              'buisness':np.nan,
              'buisness1':np.nan,
              'second':50,
              'economy':30}

In [43]:
ser = pd.Series(rail_tickt)

In [44]:
ser

first        100.0
buisness       NaN
buisness1      NaN
second        50.0
economy       30.0
dtype: float64

In [45]:
ser.interpolate() # This series should be ascending or descending for this interpolate to work

first        100.000000
buisness      83.333333
buisness1     66.666667
second        50.000000
economy       30.000000
dtype: float64

In [47]:
#dropna, fillna, mean # Are the most important here.

### Groupby Operation

It is an operation allows us to examine data on a "per category" basis
categorical column can be numbers as well 
Eg:
Category    Data value 
A          10
A          5
B          4                
B          6

Now pandas segregate this: 
A          10
A          5

B          4                
B          6

we can perform operation separately
like .mean()
.count() # counts num of rows in that category