In [1]:
import numpy as np
import pandas as pd

### Concatenation

In [2]:
data_one = {'A':['A0','A1','A2','A3'],
            'B':['B0','B1','B2','B3']}
data_two = {'C':['C0','C1','C2','C3'],
            'D':['D0','D1','D2','D3']}

In [3]:
type(data_one)

dict

In [11]:
# Convert the above into series 

series_one = pd.Series(data_one)
series_two = pd.Series(data_two)

In [12]:
print(series_one)
print(series_two)

A    [A0, A1, A2, A3]
B    [B0, B1, B2, B3]
dtype: object
C    [C0, C1, C2, C3]
D    [D0, D1, D2, D3]
dtype: object

In [13]:

df_one = pd.DataFrame(data_one)
df_two = pd.DataFrame(data_two)

print(df_one)
print(df_two)

    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3
    C   D
0  C0  D0
1  C1  D1
2  C2  D2
3  C3  D3

### concatanate along rows  (Axis -0 )

In [16]:
axis0 = pd.concat([df_one, df_two])

In [17]:
axis0

     A    B    C    D
0   A0   B0  NaN  NaN
1   A1   B1  NaN  NaN
2   A2   B2  NaN  NaN
3   A3   B3  NaN  NaN
0  NaN  NaN   C0   D0
1  NaN  NaN   C1   D1
2  NaN  NaN   C2   D2
3  NaN  NaN   C3   D3

###  Concatanate along columns (Axis 1)

In [18]:
axis1 = pd.concat([df_one, df_two], axis = 1)

In [20]:
axis1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

### Concatanate along rows with columns match up

In [21]:
df_one.columns

Index(['A', 'B'], dtype='object')

In [22]:
df_two.columns =

Index(['C', 'D'], dtype='object')

In [23]:
df_two.columns = df_one.columns

In [24]:
df_two.columns

Index(['A', 'B'], dtype='object')

In [25]:
df_two

    A   B
0  C0  D0
1  C1  D1
2  C2  D2
3  C3  D3

In [26]:
pd.concat([df_one,df_two])

    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3
0  C0  D0
1  C1  D1
2  C2  D2
3  C3  D3

### Merging of data Frames 
pd.merge(how)  # argument = how 
* inner ---> intersection in sets. 
* outer 
* left 
* right 


* primary identifier: unique per row
* before merging of tables we need to identify this uniwue identifier
* Eg: pd.merge(registrations,logins, how = 'inner', on = 'name') # inner means intersection between two set.
left:

### Merge

In [28]:
reg = pd.DataFrame({'reg_id':[1,2,3,4],
                   'name':['Andrew','Bob','Charlie','David']})
log = pd.DataFrame({'log_id':[1,2,3,4],
                   'name':['Xavier','Andrew','Yolanda','Bob']})

In [29]:
reg

   reg_id     name
0       1   Andrew
1       2      Bob
2       3  Charlie
3       4    David

In [30]:
log

   log_id     name
0       1   Xavier
1       2   Andrew
2       3  Yolanda
3       4      Bob

In [35]:
help(pd.merge) # Read      this on

Help on function merge in module pandas.core.reshape.merge:

merge(left: 'DataFrame | Series', right: 'DataFrame | Series', how: 'str' = 'inner', on: 'IndexLabel | None' = None, left_on: 'IndexLabel | None' = None, right_on: 'IndexLabel | None' = None, left_index: 'bool' = False, right_index: 'bool' = False, sort: 'bool' = False, suffixes: 'Suffixes' = ('_x', '_y'), copy: 'bool' = True, indicator: 'bool' = False, validate: 'str | None' = None) -> 'DataFrame'
    Merge DataFrame or named Series objects with a database-style join.

    A named Series object is treated as a DataFrame with a single named column.

    The join is done on columns or indexes. If joining columns on
    columns, the DataFrame indexes *will be ignored*. Otherwise if joining indexes
    on indexes or indexes on a column or columns, the index will be passed on.
    When performing a cross merge, no column specifications to merge on are
    allowed.

    .. warning::

        If both key columns contain rows where the key is a null value, those
        rows will be matched against each other. This is different from usual SQL
        join behaviour and can lead to unexpected results.

    Parameters
    ----------
    left : DataFrame
    right : DataFrame or named Series
        Object to merge with.
    how : {'left', 'right', 'outer', 'inner', 'cross'}, default 'inner'
        Type of merge to be performed.

        * left: use only keys from left frame, similar to a SQL left outer join;
          preserve key order.
        * right: use only keys from right frame, similar to a SQL right outer join;
          preserve key order.
        * outer: use union of keys from both frames, similar to a SQL full outer
          join; sort keys lexicographically.
        * inner: use intersection of keys from both frames, similar to a SQL inner
          join; preserve the order of the left keys.
        * cross: creates the cartesian product from both frames, preserves the order
          of the left keys.

          .. versionadded:: 1.2.0

    on : label or list
        Column or index level names to join on. These must be found in both
        DataFrames. If `on` is None and not merging on indexes then this defaults
        to the intersection of the columns in both DataFrames.
    left_on : label or list, or array-like
        Column or index level names to join on in the left DataFrame. Can also
        be an array or list of arrays of the length of the left DataFrame.
        These arrays are treated as if they are columns.
    right_on : label or list, or array-like
        Column or index level names to join on in the right DataFrame. Can also
        be an array or list of arrays of the length of the right DataFrame.
        These arrays are treated as if they are columns.
    left_index : bool, default False
        Use the index from the left DataFrame as the join key(s). If it is a
        MultiIndex, the number of keys in the other DataFrame (either the index
        or a number of columns) must match the number of levels.
    right_index : bool, default False
        Use the index from the right DataFrame as the join key. Same caveats as
        left_index.
    sort : bool, default False
        Sort the join keys lexicographically in the result DataFrame. If False,
        the order of the join keys depends on the join type (how keyword).
    suffixes : list-like, default is ("_x", "_y")
        A length-2 sequence where each element is optionally a string
        indicating the suffix to add to overlapping column names in
        `left` and `right` respectively. Pass a value of `None` instead
        of a string to indicate that the column name from `left` or
        `right` should be left as-is, with no suffix. At least one of the
        values must not be None.
    copy : bool, default True
        If False, avoid copy if possible.
    indicator : bool or str, default False
        If True, adds a column to the output DataFrame called "_merge" with
        information on the source of each row. The column can be given a different
        name by providing a string argument. The column will have a Categorical
        type with the value of "left_only" for observations whose merge key only
        appears in the left DataFrame, "right_only" for observations
        whose merge key only appears in the right DataFrame, and "both"
        if the observation's merge key is found in both DataFrames.

    validate : str, optional
        If specified, checks if merge is of specified type.

        * "one_to_one" or "1:1": check if merge keys are unique in both
          left and right datasets.
        * "one_to_many" or "1:m": check if merge keys are unique in left
          dataset.
        * "many_to_one" or "m:1": check if merge keys are unique in right
          dataset.
        * "many_to_many" or "m:m": allowed, but does not result in checks.

    Returns
    -------
    DataFrame
        A DataFrame of the two merged objects.

    See Also
    --------
    merge_ordered : Merge with optional filling/interpolation.
    merge_asof : Merge on nearest keys.
    DataFrame.join : Similar method using indices.

    Notes
    -----
    Support for specifying index levels as the `on`, `left_on`, and
    `right_on` parameters was added in version 0.23.0
    Support for merging named Series objects was added in version 0.24.0

    Examples
    --------
    >>> df1 = pd.DataFrame({'lkey': ['foo', 'bar', 'baz', 'foo'],
    ...                     'value': [1, 2, 3, 5]})
    >>> df2 = pd.DataFrame({'rkey': ['foo', 'bar', 'baz', 'foo'],
    ...                     'value': [5, 6, 7, 8]})
    >>> df1
        lkey value
    0   foo      1
    1   bar      2
    2   baz      3
    3   foo      5
    >>> df2
        rkey value
    0   foo      5
    1   bar      6
    2   baz      7
    3   foo      8

    Merge df1 and df2 on the lkey and rkey columns. The value columns have
    the default suffixes, _x and _y, appended.

    >>> df1.merge(df2, left_on='lkey', right_on='rkey')
      lkey  value_x rkey  value_y
    0  foo        1  foo        5
    1  foo        1  foo        8
    2  foo        5  foo        5
    3  foo        5  foo        8
    4  bar        2  bar        6
    5  baz        3  baz        7

    Merge DataFrames df1 and df2 with specified left and right suffixes
    appended to any overlapping columns.

    >>> df1.merge(df2, left_on='lkey', right_on='rkey',
    ...           suffixes=('_left', '_right'))
      lkey  value_left rkey  value_right
    0  foo           1  foo            5
    1  foo           1  foo            8
    2  foo           5  foo            5
    3  foo           5  foo            8
    4  bar           2  bar            6
    5  baz           3  baz            7

    Merge DataFrames df1 and df2, but raise an exception if the DataFrames have
    any overlapping columns.

    >>> df1.merge(df2, left_on='lkey', right_on='rkey', suffixes=(False, False))
    Traceback (most recent call last):
    ...
    ValueError: columns overlap but no suffix specified:
        Index(['value'], dtype='object')

    >>> df1 = pd.DataFrame({'a': ['foo', 'bar'], 'b': [1, 2]})
    >>> df2 = pd.DataFrame({'a': ['foo', 'baz'], 'c': [3, 4]})
    >>> df1
          a  b
    0   foo  1
    1   bar  2
    >>> df2
          a  c
    0   foo  3
    1   baz  4

    >>> df1.merge(df2, how='inner', on='a')
          a  b  c
    0   foo  1  3

    >>> df1.merge(df2, how='left', on='a')
          a  b  c
    0   foo  1  3.0
    1   bar  2  NaN

    >>> df1 = pd.DataFrame({'left': ['foo', 'bar']})
    >>> df2 = pd.DataFrame({'right': [7, 8]})
    >>> df1
        left
    0   foo
    1   bar
    >>> df2
        right
    0   7
    1   8

    >>> df1.merge(df2, how='cross')
       left  right
    0   foo      7
    1   foo      8
    2   bar      7
    3   bar      8

### Inner

In [36]:
pd.merge(reg,log,how = 'inner', on = 'name') # Common

   reg_id    name  log_id
0       1  Andrew       2
1       2     Bob       4

In [38]:
pd.merge(reg,log,how = 'inner') # Common

   reg_id    name  log_id
0       1  Andrew       2
1       2     Bob       4

### Left

In [39]:
pd.merge(reg,log,how = 'left', on = 'name')

   reg_id     name  log_id
0       1   Andrew     2.0
1       2      Bob     4.0
2       3  Charlie     NaN
3       4    David     NaN

### Right

In [41]:
pd.merge(reg,log,how = 'right', on = 'name')

   reg_id     name  log_id
0     NaN   Xavier       1
1     1.0   Andrew       2
2     NaN  Yolanda       3
3     2.0      Bob       4

###  outer

In [43]:
pd.merge(reg,log,how = 'outer', on = 'name') # all

   reg_id     name  log_id
0     1.0   Andrew     2.0
1     2.0      Bob     4.0
2     3.0  Charlie     NaN
3     4.0    David     NaN
4     NaN   Xavier     1.0
5     NaN  Yolanda     3.0

### Join on index or columns

In [44]:
reg

   reg_id     name
0       1   Andrew
1       2      Bob
2       3  Charlie
3       4    David

In [45]:
log

   log_id     name
0       1   Xavier
1       2   Andrew
2       3  Yolanda
3       4      Bob

In [48]:
reg = reg.set_index('name') # so that the unique identifier we can make it as an index

KeyError: "None of ['name'] are in the columns"

In [49]:
reg

         reg_id
name
Andrew        1
Bob           2
Charlie       3
David         4

In [50]:
log = log.set_index('name') # so that the unique identifier we can make it as an index

In [51]:
log

         log_id
name
Xavier        1
Andrew        2
Yolanda       3
Bob           4

In [53]:
pd.merge(reg, log, left_index = True, right_on = 'name') #we are taking left data that is reg and joining.

        reg_id  log_id
name
Andrew       1       2
Bob          2       4

In [54]:
type(np.nan)

float

### Dealing with different key column names

In [56]:
reg = pd.DataFrame({'reg_id':[1,2,3,4],
                   'reg_name':['Andrew','Bob','Charlie','David']})
log = pd.DataFrame({'log_id':[1,2,3,4],
                   'name':['Xavier','Andrew','Yolanda','Bob']})

In [57]:
reg

   reg_id reg_name
0       1   Andrew
1       2      Bob
2       3  Charlie
3       4    David

In [58]:
log

   log_id     name
0       1   Xavier
1       2   Andrew
2       3  Yolanda
3       4      Bob

In [59]:
pd.merge(reg, log, left_on = 'reg_name', right_on = 'name')

   reg_id reg_name  log_id    name
0       1   Andrew       2  Andrew
1       2      Bob       4     Bob

In [60]:
pd.merge(reg, log, left_on = 'reg_name', right_on = 'name').drop('reg_name', axis = 1)

   reg_id  log_id    name
0       1       2  Andrew
1       2       4     Bob

In [61]:
reg = pd.DataFrame({'id':[1,2,3,4],
                   'name':['Andrew','Bob','Charlie','David']})
log = pd.DataFrame({'id':[1,2,3,4],
                   'name':['Xavier','Andrew','Yolanda','Bob']})

In [62]:
reg

   id     name
0   1   Andrew
1   2      Bob
2   3  Charlie
3   4    David

In [63]:
log

   id     name
0   1   Xavier
1   2   Andrew
2   3  Yolanda
3   4      Bob

In [64]:
pd.merge(reg, log, on = 'name')

   id_x    name  id_y
0     1  Andrew     2
1     2     Bob     4

In [70]:
pd.merge(reg, log, on = 'name', suffixes=('_reg','_log')) # to customize since we had two col's had same name.

   id_reg    name  id_log
0       1  Andrew       2
1       2     Bob       4